### ISSUE TITLE
Can't deploy it

### ISSUE THREAD

**Issue by NoodlesDev987** [Chasing66/peer2profit-heroku#4]
Heroku has blocked me deploying it :/

**Comment by NoodlesDev987** [comment]
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy

**Comment by NoodlesDev987** [comment]
@Chasing66 Does it work for you?

**Comment by enwaiax** [comment]
yes, it's the same. Heroku has blocked it

**Comment by airovigo** [comment]
> yes, it's the same. Heroku has blocked it




it is possible to transfer to okteto.com netlify.com

**Comment by enwaiax** [comment]
My okteto account is disable due to running it, so okteto is not allowed to run it.
netlify is used for static web, not suitabe for this, you need find a container or K8s platform
@airovigo
